spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_auth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    pool-size: 30