spring:
  datasource:
    jdbc-url: jdbc:mysql://smart-mysql:3306/smart_auth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Greate@20200216
eureka:
  client:
    serviceUrl:
      defaultZone: http://smart-eureka:8761/eureka/
logging:
  level:
    root: DEBUG
    com.lee: DEBUG