spring:
  datasource:
    jdbc-url: jdbc:mysql://smart-mysql:3306/smart_auth?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Greate@20200216
    driverClassName: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    root: DEBUG
    com.lee: DEBUG
    org.springframework.security: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://smart-eureka:8761/eureka/
    register-with-eureka: true
    fetch-registry: true