spring:
  datasource:
    jdbc-url: jdbc:mysql://smart-mysql:3306/smart_report?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Greate@20200216
    driverClassName: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://smart-eureka:8761/eureka/
logging:
  level:
    root: DEBUG
    com.lee: DEBUG
security:
  oauth2:
    client:
      client-id: resource
      client-secret: resource
      scope: server
    resource:
      tokenInfoUri: http://smart-auth:8400/oauth/check_token
##内部服务调用，跳过资源服务器token校验
white-list:
  urls:
    - /user/internal/*