server:
  port: 2080
spring:
  application:
    name: smart-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        ##配置本地路径
        native:
          search-locations: classpath:properties/