spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/smart_report?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: DEBUG
    com.lee: DEBUG