spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        id: smart-auth
        uri: lb://smart-auth-server
        predicates:
          - Path=/auth/**
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
      timeout: 0
logging:
  level:
    root: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
